# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gus Cuddy
tagline: Brooklyn-based writer, actor, & maker.
email: gus.cuddy@gmail.com
description: Gus is writing about theatre, culture, creativity, society, and the future. He also performs and makes theatre and movies.
url: https://guscuddy.com

author:
  name: Gus Cuddy
  twitter: guscuddy
twitter:
  username: guscuddy
social:
  name: Gus Cuddy
  links:
    - https://twitter.com/guscuddy
    - https://facebook.com/guscuddy
    - https://instagram.com/guscuddy
github_username: gcuddy

future: false

paginate: 10
paginate_path: "/blog/page:num/"

collections:
  books:
    output: true
  booknotes:
    output: true
  plays:
    output: true
  tweetstorms:
    output: true
  shows:
    output: true

# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
